language: go
go:
  - 1.8.x
  - master
install: true
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.8
    - IMAGE_NAME=orcinustools/omura
notifications:
  email:
    on_success: change
    on_failure: alwayss